# Generated by Django 4.0 on 2022-12-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddTeacher',
            new_name='Teacher',
        ),
    ]
