# Generated by Django 4.0 on 2022-12-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_addteacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Education',
            field=models.CharField(max_length=100),
        ),
    ]
