# Generated by Django 4.0 on 2022-12-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_teacher_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Due',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='Total',
            field=models.IntegerField(default=0),
        ),
    ]
